export const CHAT_EVENTS = {
  CREATE_CONVERSATION: "CREATE_CONVERSATION",
  SEND_MESSAGE: "SEND_MESSAGE",
  FETCH_CONVERSATIONS: "FETCH_CONVERSATIONS",
  FETCH_MESSAGES: "FETCH_MESSAGES",
  CONVERSATION_CREATED: "CONVERSATION_CREATED",
  MESSAGE_SENT: "MESSAGE_SENT",
};
