name: Build and deploy Node.js app to Azure Web App - dumdum12

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      # Modified zip step to handle the buffer overflow issue
      - name: Prepare and zip artifact
        run: |
          # Remove unnecessary files before zipping
          rm -rf node_modules/.cache
          rm -rf coverage
          rm -rf .git
          # Create zip with better handling
          zip -r release.zip . \
            -x "node_modules/.cache/*" \
            -x "coverage/*" \
            -x ".git/*" \
            -x ".github/*" \
            -x "*.log"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Create deployment directory
        run: |
          mkdir deploy
          mv release.zip deploy/
          cd deploy
          unzip release.zip
          rm release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CBF52DCCC2AA4E9DBE60486338CAC2BA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FD198043890F49BD8C02ED0D9C7221E3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_96763CFDCE274408BAB7C80B2BBAA062 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dumdum12'
          slot-name: 'Production'
          package: ./deploy